import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ArrowLeft, Boxes, Building2, ClipboardPlus, Package, Plus, Search } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useProfile } from "@/hooks/use-profile";
import { getOwnerProducts } from "@/lib/team.functions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatQty, packSize, toPieces } from "@/lib/units";

export const Route = createFileRoute("/_authenticated/master-stock")({ head: () => ({ meta: [{ title: "Stok Gudang — Sales Pouch" }, { name: "description", content: "Pantau dan catat stok fisik setiap produk di seluruh lokasi usaha." }, { property: "og:title", content: "Stok Gudang — Sales Pouch" }, { property: "og:description", content: "Pantau dan catat stok fisik setiap produk di seluruh lokasi usaha." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: MasterStockPage });
type Setup = { id: string; mode: "migration" | "from_start"; status: "active" | "finalized" };
type ProductStock = { product_id: string; product_name: string; global_quantity: number };
type Product = { id: string; name: string; pcs_per_pack: number };
type Location = { id: string; name: string; location_type: "warehouse" | "outlet" | "sales" };
type Opening = { product_id: string; location_id: string; quantity: number };
type Movement = { product_id: string; from_location_id: string | null; to_location_id: string | null; quantity: number };
const locationLabel = (type: Location["location_type"]) => type === "warehouse" ? "Gudang" : type === "outlet" ? "Toko" : "Sales";

function MasterStockPage() {
  const { data: account, isLoading: accountLoading } = useProfile();
  const queryClient = useQueryClient();
  const fetchOwnerProducts = useServerFn(getOwnerProducts);
  const [search, setSearch] = useState("");
  const [locationFilter, setLocationFilter] = useState<"all" | "warehouse" | "outlet" | "sales">("all");
  const [showProduction, setShowProduction] = useState(false);
  const [productionLocation, setProductionLocation] = useState("");
  const [productionProduct, setProductionProduct] = useState("");
  const [productionPack, setProductionPack] = useState("");
  const [productionPcs, setProductionPcs] = useState("");
  const [productionDate, setProductionDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [productionNote, setProductionNote] = useState("");
  const [savingProduction, setSavingProduction] = useState(false);
  const [productionMessage, setProductionMessage] = useState("");
  const [showOpening, setShowOpening] = useState(false);
  const [openingLocation, setOpeningLocation] = useState("");
  const [openingProduct, setOpeningProduct] = useState("");
  const [openingPack, setOpeningPack] = useState("");
  const [openingPcs, setOpeningPcs] = useState("");
  const [openingNote, setOpeningNote] = useState("");
  const [savingOpening, setSavingOpening] = useState(false);
  const [openingMessage, setOpeningMessage] = useState("");

  const { data: setup, isLoading: setupLoading } = useQuery<Setup | null>({ queryKey: ["master-stock-setup", account?.ownerId], enabled: !!account?.ownerId, queryFn: async () => { const { data, error } = await (supabase as any).from("stock_setups").select("id,mode,status").eq("owner_id", account!.ownerId).maybeSingle(); if (error) throw error; return data; } });
  const { data: global = [] } = useQuery<ProductStock[]>({ queryKey: ["master-stock-global", account?.ownerId], enabled: !!account?.ownerId && setup?.status === "finalized", queryFn: async () => { const { data, error } = await (supabase as any).from("master_stock_global").select("product_id,product_name,global_quantity").eq("owner_id", account!.ownerId).order("product_name"); if (error) throw error; return data ?? []; } });
  const { data: products = [] } = useQuery<Product[]>({ queryKey: ["master-stock-products", account?.ownerId], enabled: !!account?.ownerId && setup?.status === "finalized", queryFn: async () => { const data = await fetchOwnerProducts(); return (data ?? []).filter((p: any) => p.is_active !== false).map((p: any) => ({ id: p.id, name: p.name, pcs_per_pack: Math.max(1, Number(p.pcs_per_pack) || 1) })); } });
  const { data: locations = [] } = useQuery<Location[]>({ queryKey: ["master-stock-locations", account?.ownerId], enabled: !!account?.ownerId && setup?.status === "finalized", queryFn: async () => { const { data, error } = await (supabase as any).from("stock_locations").select("id,name,location_type").eq("owner_id", account!.ownerId).eq("is_active", true).order("location_type").order("name"); if (error) throw error; return data ?? []; } });
  const { data: openings = [] } = useQuery<Opening[]>({ queryKey: ["master-stock-openings", setup?.id], enabled: !!setup?.id && setup.status === "finalized", queryFn: async () => { const { data, error } = await (supabase as any).from("stock_opening_items").select("product_id,location_id,quantity").eq("setup_id", setup!.id); if (error) throw error; return data ?? []; } });
  const { data: movements = [] } = useQuery<Movement[]>({ queryKey: ["master-stock-movements", account?.ownerId], enabled: !!account?.ownerId && setup?.status === "finalized", queryFn: async () => { const { data, error } = await (supabase as any).from("stock_movements").select("product_id,from_location_id,to_location_id,quantity").eq("owner_id", account!.ownerId); if (error) throw error; return data ?? []; } });

  const selectedProductionProduct = products.find((p) => p.id === productionProduct);
  const productionPackSize = selectedProductionProduct?.pcs_per_pack ?? 1;
  const productionPacks = Math.max(0, Number(productionPack) || 0);
  const productionRemainder = Math.max(0, Number(productionPcs) || 0);
  const productionQuantity = productionPacks * productionPackSize + productionRemainder;
  const selectedOpeningProduct = products.find((p) => p.id === openingProduct);
  const openingPackSize = packSize(selectedOpeningProduct?.pcs_per_pack);
  const openingQuantity = toPieces(Math.max(0, Number(openingPack) || 0), Math.max(0, Number(openingPcs) || 0), openingPackSize);

  const stockByProduct = useMemo(() => { const result = new Map<string, number>(); global.forEach((row) => result.set(row.product_id, Math.max(0, Number(row.global_quantity) || 0))); return result; }, [global]);
  const productCount = products.length;
  const globalTotal = useMemo(() => products.reduce((sum, p) => sum + (stockByProduct.get(p.id) ?? 0), 0), [products, stockByProduct]);
  const productLocationStock = useMemo(() => { const result = new Map<string, Map<string, number>>(); const add = (productId: string, locationId: string, amount: number) => { if (!result.has(productId)) result.set(productId, new Map()); const byLocation = result.get(productId)!; byLocation.set(locationId, (byLocation.get(locationId) ?? 0) + amount); }; openings.forEach((x) => add(x.product_id, x.location_id, Number(x.quantity) || 0)); movements.forEach((x) => { if (x.from_location_id) add(x.product_id, x.from_location_id, -(Number(x.quantity) || 0)); if (x.to_location_id) add(x.product_id, x.to_location_id, Number(x.quantity) || 0); }); return result; }, [openings, movements]);
  const visibleProducts = useMemo(() => { const q = search.trim().toLowerCase(); return products.filter((p) => { if (q && !p.name.toLowerCase().includes(q)) return false; if (locationFilter === "all") return true; const byLocation = productLocationStock.get(p.id); return locations.filter((l) => l.location_type === locationFilter).some((l) => (byLocation?.get(l.id) ?? 0) > 0); }); }, [products, search, locationFilter, productLocationStock, locations]);

  const saveProduction = async () => {
    setProductionMessage("");
    if (!productionLocation || !productionProduct || productionQuantity <= 0) { setProductionMessage("Pilih lokasi, produk, dan isi jumlah stok lebih dari 0."); return; }
    if (!/^\d*$/.test(productionPack) || !/^\d*$/.test(productionPcs) || productionRemainder >= productionPackSize) { setProductionMessage(`Sisa pcs harus 0–${productionPackSize - 1} untuk produk ini.`); return; }
    setSavingProduction(true);
    const { error } = await (supabase as any).from("stock_movements").insert({ owner_id: account!.ownerId, product_id: productionProduct, movement_type: "production", from_location_id: null, to_location_id: productionLocation, quantity: productionQuantity, reference_type: "production", notes: productionNote.trim() || null, occurred_at: new Date(`${productionDate}T12:00:00`).toISOString() });
    setSavingProduction(false);
    if (error) { setProductionMessage(error.message || "Gagal menyimpan stok distribusi."); return; }
    await Promise.all([queryClient.invalidateQueries({ queryKey: ["master-stock-global", account?.ownerId] }), queryClient.invalidateQueries({ queryKey: ["master-stock-movements", account?.ownerId] })]);
    setProductionPack(""); setProductionPcs(""); setProductionNote(""); setProductionMessage(`Stok distribusi ${productionQuantity.toLocaleString("id-ID")} pcs berhasil ditambahkan.`);
  };

  const saveOpeningSnapshot = async () => {
    setOpeningMessage("");
    if (!openingLocation || !openingProduct) { setOpeningMessage("Pilih lokasi dan produk terlebih dahulu."); return; }
    if (!/^\d*$/.test(openingPack) || !/^\d*$/.test(openingPcs) || Number(openingPcs || 0) >= openingPackSize) { setOpeningMessage(`Sisa pcs harus 0–${openingPackSize - 1} untuk produk ini.`); return; }
    if (openingPack === "" && openingPcs === "") { setOpeningMessage("Isi jumlah fisik dalam pack atau pcs."); return; }
    if (openingNote.trim().length > 250) { setOpeningMessage("Catatan maksimal 250 karakter."); return; }
    setSavingOpening(true);
    const { error } = await (supabase as any).rpc("record_physical_opening_snapshot", { _location_id: openingLocation, _product_id: openingProduct, _physical_quantity: openingQuantity, _counted_at: new Date().toISOString(), _note: openingNote.trim() || null });
    setSavingOpening(false);
    if (error) { setOpeningMessage(error.message || "Stok awal gagal disimpan."); return; }
    await Promise.all([queryClient.invalidateQueries({ queryKey: ["master-stock-global", account?.ownerId] }), queryClient.invalidateQueries({ queryKey: ["master-stock-movements", account?.ownerId] }), queryClient.invalidateQueries({ queryKey: ["visit-sales-stock"] })]);
    setOpeningPack(""); setOpeningPcs(""); setOpeningNote("");
    setOpeningMessage(`Snapshot fisik ${formatQty(openingQuantity, openingPackSize)} berhasil disimpan.`);
  };

  if (accountLoading || setupLoading) return <main className="mx-auto max-w-md px-4 pt-12 text-center text-sm text-muted-foreground">Memuat Stok Gudang…</main>;
  if (account?.role !== "owner") return <main className="mx-auto max-w-md px-4 pt-12 text-center text-destructive">Stok Gudang hanya dapat dilihat Owner.</main>;
  if (!setup) return <main className="mx-auto min-h-screen max-w-md px-4 pb-10 pt-5"><Link to="/dashboard" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Kembali</Link><header className="mt-5 flex items-start gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-100 text-blue-700"><Boxes className="h-6 w-6" /></div><div><h1 className="text-2xl font-bold tracking-tight">Stok Gudang</h1><p className="mt-1 text-sm text-muted-foreground">Mulai dari Stok Pembukaan sebelum memantau stok Gudang.</p></div></header><section className="mt-6 rounded-2xl border bg-card p-5 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-orange-100 text-orange-700"><Boxes className="h-7 w-7" /></div><h2 className="mt-4 text-lg font-bold">Stok Pembukaan</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Tentukan mode usaha dan catat stok fisik awal per Gudang, Toko, atau Sales. Setelah final, halaman ini otomatis berubah menjadi monitoring Stok Global.</p><Button asChild className="mt-5 h-11 w-full rounded-xl"><Link to="/stock-opening">Mulai Stok Pembukaan</Link></Button></section></main>;
  if (setup.status === "active") return <main className="mx-auto min-h-screen max-w-md px-4 pb-10 pt-5"><Link to="/dashboard" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Kembali</Link><header className="mt-5"><div className="font-mono text-[11px] uppercase tracking-[0.2em] text-blue-700">Stok Gudang</div><h1 className="mt-1 text-2xl font-bold tracking-tight">Stok Pembukaan</h1><p className="mt-1 text-sm text-muted-foreground">Setup sedang berjalan. Lanjutkan pengisian, lalu setelah final Stok Gudang akan menampilkan stok global.</p></header><section className="mt-5 rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-orange-100 p-3 text-orange-700"><Boxes className="h-5 w-5" /></div><div><div className="text-xs text-muted-foreground">Mode</div><b>{setup.mode === "migration" ? "Migrasi Usaha" : "Mulai dari Awal"}</b></div></div><Button asChild className="mt-5 h-11 w-full rounded-xl"><Link to="/stock-opening">Lanjutkan Stok Pembukaan</Link></Button></section></main>;

  return <main className="mx-auto min-h-screen max-w-md px-4 pb-10 pt-5">
    <Link to="/dashboard" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Kembali</Link>
    <header className="mt-5 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-100 text-blue-700"><Boxes className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="font-mono text-[11px] uppercase tracking-[0.2em] text-blue-700">Stok Gudang</div><h1 className="text-2xl font-bold tracking-tight">Stok Produk</h1></div><Button type="button" size="sm" className="shrink-0" onClick={() => { setShowOpening(true); setOpeningMessage(""); }}><ClipboardPlus className="mr-1 h-4 w-4" /> Input Stok Awal</Button></header>
    <section className="mt-5 rounded-2xl border bg-card p-5 shadow-sm"><div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Ringkasan usaha</div><div className="mt-2 flex items-end justify-between gap-3"><div><div className="text-3xl font-bold tracking-tight">{productCount.toLocaleString("id-ID")}</div><div className="text-sm text-muted-foreground">produk</div></div><div className="text-right"><div className="text-xl font-bold">{globalTotal.toLocaleString("id-ID")} pcs</div><div className="text-xs text-muted-foreground">total stok semua produk</div></div></div></section>
    <section className="mt-3 rounded-2xl border bg-orange-50/70 p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-bold">Stok Distribusi</div><p className="mt-1 text-xs leading-5 text-muted-foreground">Catat stok yang masuk atau restock setelah sistem mulai digunakan.</p></div><Button type="button" className="shrink-0 rounded-xl" onClick={() => { setShowProduction((v) => !v); setProductionMessage(""); }}>{showProduction ? "Tutup" : <><Plus className="mr-1 h-4 w-4" /> Tambah Stok Distribusi</>}</Button></div>
      {showProduction && <div className="mt-4 space-y-3 border-t pt-4"><div><label className="mb-1 block text-xs font-medium">Lokasi tujuan</label><select value={productionLocation} onChange={(e) => setProductionLocation(e.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="">Pilih lokasi…</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name} — {locationLabel(l.location_type)}</option>)}</select></div><div><label className="mb-1 block text-xs font-medium">Produk</label><select value={productionProduct} onChange={(e) => { setProductionProduct(e.target.value); setProductionPack(""); setProductionPcs(""); }} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="">Pilih produk…</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name} — 1 pack = {p.pcs_per_pack} pcs</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-xs font-medium">Pack</label><Input type="number" min="0" step="1" value={productionPack} onChange={(e) => setProductionPack(e.target.value)} placeholder="0" className="h-11 rounded-xl" /></div><div><label className="mb-1 block text-xs font-medium">Pcs sisa</label><Input type="number" min="0" step="1" value={productionPcs} onChange={(e) => setProductionPcs(e.target.value)} placeholder="0" className="h-11 rounded-xl" /></div></div>{productionProduct && <div className="rounded-xl bg-muted/50 px-3 py-2 text-xs text-muted-foreground">Konversi: <b className="text-foreground">{productionQuantity.toLocaleString("id-ID")} pcs</b> · maksimal sisa pcs: {productionPackSize - 1}</div>}<div><label className="mb-1 block text-xs font-medium">Tanggal</label><Input type="date" value={productionDate} onChange={(e) => setProductionDate(e.target.value)} className="h-11 rounded-xl" /></div><div><label className="mb-1 block text-xs font-medium">Catatan <span className="font-normal text-muted-foreground">(opsional)</span></label><Input value={productionNote} onChange={(e) => setProductionNote(e.target.value)} placeholder="Contoh: Produksi batch pagi" className="h-11 rounded-xl" /></div>{productionMessage && <div className={`rounded-xl px-3 py-2 text-xs ${productionMessage.includes("berhasil") ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{productionMessage}</div>}<Button type="button" disabled={savingProduction} className="h-11 w-full rounded-xl" onClick={saveProduction}>{savingProduction ? "Menyimpan…" : "Simpan Stok Distribusi"}</Button></div>}
    </section>
    <div className="mt-5 flex gap-2"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari produk…" className="h-11 rounded-xl pl-9" /></div><select value={locationFilter} onChange={(e) => setLocationFilter(e.target.value as typeof locationFilter)} className="h-11 rounded-xl border bg-background px-3 text-sm"><option value="all">Semua lokasi</option><option value="warehouse">Gudang</option><option value="outlet">Toko</option><option value="sales">Sales</option></select></div>
    <section className="mt-3 overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="divide-y">{visibleProducts.map((p) => { const byLocation = productLocationStock.get(p.id) ?? new Map<string, number>(); return <div key={p.id} className="px-4 py-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="font-medium truncate">{p.name}</div><div className="text-xs text-muted-foreground">1 pack = {p.pcs_per_pack} pcs</div></div><div className="text-right"><div className="font-bold">{formatQty(stockByProduct.get(p.id) ?? 0, p.pcs_per_pack)}</div><div className="text-xs text-muted-foreground">global</div></div></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs">{locations.filter((l) => l.location_type === "warehouse").slice(0, 1).map((l) => <div key={l.id} className="rounded-lg bg-muted/40 p-2"><div className="text-muted-foreground">Gudang</div><b>{formatQty(byLocation.get(l.id) ?? 0, p.pcs_per_pack)}</b></div>)}{locations.filter((l) => l.location_type === "sales").slice(0, 1).map((l) => <div key={l.id} className="rounded-lg bg-muted/40 p-2"><div className="text-muted-foreground">Sales</div><b>{formatQty(byLocation.get(l.id) ?? 0, p.pcs_per_pack)}</b></div>)}{locations.filter((l) => l.location_type === "outlet").slice(0, 1).map((l) => <div key={l.id} className="rounded-lg bg-muted/40 p-2"><div className="text-muted-foreground">Toko</div><b>{formatQty(byLocation.get(l.id) ?? 0, p.pcs_per_pack)}</b></div>)}</div></div>; })}{visibleProducts.length === 0 && <div className="px-4 py-10 text-center text-sm text-muted-foreground">Tidak ada produk yang sesuai.</div>}</div></section>
    <Dialog open={showOpening} onOpenChange={setShowOpening}><DialogContent><DialogHeader><DialogTitle>Input Stok Awal</DialogTitle><DialogDescription>Catat snapshot fisik awal per lokasi sebelum stok berjalan.</DialogDescription></DialogHeader><div className="space-y-3"><div><label className="mb-1 block text-xs font-medium">Lokasi</label><select value={openingLocation} onChange={(e) => setOpeningLocation(e.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="">Pilih lokasi…</option>{locations.map((l) => <option key={l.id} value={l.id}>{l.name} — {locationLabel(l.location_type)}</option>)}</select></div><div><label className="mb-1 block text-xs font-medium">Produk</label><select value={openingProduct} onChange={(e) => { setOpeningProduct(e.target.value); setOpeningPack(""); setOpeningPcs(""); }} className="h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="">Pilih produk…</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name} — 1 pack = {p.pcs_per_pack} pcs</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><label className="mb-1 block text-xs font-medium">Pack</label><Input type="number" min="0" step="1" value={openingPack} onChange={(e) => setOpeningPack(e.target.value)} placeholder="0" className="h-11 rounded-xl" /></div><div><label className="mb-1 block text-xs font-medium">Pcs sisa</label><Input type="number" min="0" step="1" value={openingPcs} onChange={(e) => setOpeningPcs(e.target.value)} placeholder="0" className="h-11 rounded-xl" /></div></div>{openingProduct && <div className="rounded-xl bg-muted/50 px-3 py-2 text-xs text-muted-foreground">Konversi: <b className="text-foreground">{openingQuantity.toLocaleString("id-ID")} pcs</b> · maksimal sisa pcs: {openingPackSize - 1}</div>}<div><label className="mb-1 block text-xs font-medium">Catatan <span className="font-normal text-muted-foreground">(opsional)</span></label><Input value={openingNote} onChange={(e) => setOpeningNote(e.target.value)} placeholder="Contoh: Hitung fisik awal" className="h-11 rounded-xl" /></div>{openingMessage && <div className={`rounded-xl px-3 py-2 text-xs ${openingMessage.includes("berhasil") ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{openingMessage}</div>}<Button type="button" disabled={savingOpening} className="h-11 w-full rounded-xl" onClick={saveOpeningSnapshot}>{savingOpening ? "Menyimpan…" : "Simpan Stok Awal"}</Button></div></DialogContent></Dialog>
  </main>;
}
