import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Printer, Share2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useProfile } from "@/hooks/use-profile";
import { rp, type LineItem, type NewItem } from "@/lib/visit";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_authenticated/receipt/$id")({
  head: () => ({ meta: [{ title: "Nota — Sales Pouch" }, { name: "description", content: "Nota thermal digital." }] }),
  component: ReceiptPage,
});

const fmtDate = (d: string) => new Date(d).toLocaleString("id-ID", { dateStyle: "medium", timeStyle: "short" });

function ReceiptPage() {
  const { id } = Route.useParams();
  const { data: p } = useProfile();
  const { data: t, isLoading, error } = useQuery({
    queryKey: ["receipt", id],
    queryFn: async () => {
      const { data, error } = await supabase.from("transactions").select("*, outlets(name)").eq("id", id).single();
      if (error) throw error;
      return data;
    },
  });

  if (isLoading) return <p className="p-10 text-center text-muted-foreground">Memuat nota…</p>;
  if (error || !t) return <p className="p-10 text-center text-destructive">Nota tidak ditemukan.</p>;

  const items = (t.line_items as LineItem[]) ?? [];
  const newItems = (t.new_consignment_items as NewItem[]) ?? [];
  const prevDebt = Number(t.previous_debt);
  const business = p?.profile?.business_name ?? "";
  const store = (t.outlets as { name: string } | null)?.name ?? "-";

  function asText() {
    const L: string[] = [business.toUpperCase(), `No Nota : ${t!.receipt_number}`, `Toko    : ${store}`, `Sales   : ${t!.sales_name}`, `Tanggal : ${fmtDate(t!.visit_date)}`, "--------------------------------"];
    items.forEach((i) => {
      L.push(i.name);
      if (t!.transaction_type === "Consignment") L.push(`  Titip Sebelumnya: ${i.prev_stock}`);
      L.push(`  ${i.sold} x ${rp(i.price)} = ${rp(i.subtotal)}`);
      if (i.returned) L.push(`  Retur: ${i.returned}`);
    });
    L.push("--------------------------------");
    if (prevDebt > 0) {
      L.push(`Utang Sebelumnya : ${rp(prevDebt)}`, `Total Penjualan  : ${rp(t!.total_sales)}`, `Total Tagihan    : ${rp(t!.total_due)}`, `Dibayar          : ${rp(t!.amount_paid)}`, `Sisa Utang       : ${rp(t!.remaining_debt)}`);
    } else {
      L.push(`TOTAL TAGIHAN / DIBAYAR : ${rp(t!.total_due)} (Status: Lunas / Tanpa Tunggakan) ✅`);
    }
    if (newItems.length) { L.push("--------------------------------", "TITIP BARU HARI INI"); newItems.forEach((n) => L.push(`  ${n.name}: ${n.qty} x ${rp(n.price)}`)); }
    if (t!.custom_note) L.push("", t!.custom_note);
    L.push("", "Terima Kasih 🙏", "*Generated by Sales Pouch*");
    return L.join("\n");
  }

  async function share() {
    const text = asText();
    try {
      if (navigator.share) await navigator.share({ title: t!.receipt_number, text });
      else { await navigator.clipboard.writeText(text); toast.success("Nota disalin"); }
    } catch { /* cancelled */ }
  }

  const hr = <div className="my-2 border-t border-dashed border-foreground/40" />;

  return (
    <main className="mx-auto min-h-screen max-w-md px-5 pb-10 pt-6">
      <div className="flex items-center justify-between print:hidden">
        <Link to="/dashboard" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4" />Beranda</Link>
      </div>

      <article className="mx-auto mt-4 w-full max-w-[340px] bg-card px-5 py-6 font-mono text-[12px] leading-relaxed text-foreground shadow-lg [clip-path:polygon(0_0,100%_0,100%_calc(100%-8px),95%_100%,90%_calc(100%-8px),85%_100%,80%_calc(100%-8px),75%_100%,70%_calc(100%-8px),65%_100%,60%_calc(100%-8px),55%_100%,50%_calc(100%-8px),45%_100%,40%_calc(100%-8px),35%_100%,30%_calc(100%-8px),25%_100%,20%_calc(100%-8px),15%_100%,10%_calc(100%-8px),5%_100%,0_calc(100%-8px))] print:shadow-none">
        <div className="text-center text-sm font-semibold uppercase">{business}</div>
        {hr}
        <Row k="No Nota" v={t.receipt_number} />
        <Row k="Toko" v={store} />
        <Row k="Sales" v={t.sales_name} />
        <Row k="Tanggal" v={fmtDate(t.visit_date)} />
        {hr}
        {items.length === 0 && <div className="text-center text-muted-foreground">— Tidak ada penjualan —</div>}
        {items.map((i, idx) => (
          <div key={idx} className="mb-2">
            <div className="font-semibold">{i.name}</div>
            {t.transaction_type === "Consignment" && <Row k="Titip Sebelumnya" v={String(i.prev_stock)} />}
            <Row k={`Terjual ${i.sold} x ${rp(i.price)}`} v={rp(i.subtotal)} />
            {t.transaction_type === "Consignment" && <Row k="Retur" v={String(i.returned)} />}
          </div>
        ))}
        {hr}
        {prevDebt > 0 ? (
          <>
            <Row k="Utang Sebelumnya" v={rp(prevDebt)} />
            <Row k="Total Penjualan" v={rp(Number(t.total_sales))} />
            <Row k="Total Tagihan" v={rp(Number(t.total_due))} bold />
            <Row k="Dibayar" v={rp(Number(t.amount_paid))} />
            <Row k="Sisa Utang" v={rp(Number(t.remaining_debt))} bold />
          </>
        ) : (
          <div className="font-semibold">
            TOTAL TAGIHAN / DIBAYAR : {rp(Number(t.total_due))} (Status: Lunas / Tanpa Tunggakan) ✅
          </div>
        )}
        {newItems.length > 0 && (
          <>
            {hr}
            <div className="font-semibold">TITIP BARU HARI INI</div>
            {newItems.map((n, idx) => <Row key={idx} k={`${n.name} (${n.qty})`} v={`@ ${rp(n.price)}`} />)}
          </>
        )}
        {hr}
        {t.custom_note && <p className="mb-2 whitespace-pre-wrap text-xs text-gray-500">{t.custom_note}</p>}
        <div className="text-center">Terima Kasih 🙏</div>
        <div className="text-center italic">*Generated by Sales Pouch*</div>
      </article>

      <div className="mt-6 grid grid-cols-2 gap-3 print:hidden">
        <Button variant="outline" className="h-12" onClick={() => window.print()}><Printer className="mr-1 h-4 w-4" />Cetak</Button>
        <Button className="h-12" onClick={share}><Share2 className="mr-1 h-4 w-4" />Bagikan</Button>
      </div>
    </main>
  );
}

function Row({ k, v, bold }: { k: string; v: string; bold?: boolean }) {
  return <div className={`flex justify-between gap-3 ${bold ? "font-semibold" : ""}`}><span>{k}</span><span className="text-right">{v}</span></div>;
}
