/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminStockResetRouteImport } from './routes/_authenticated/admin-stock-reset'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedMasterStockRouteImport } from './routes/_authenticated/master-stock'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedOperasionalSalesRouteImport } from './routes/_authenticated/operasional-sales'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedOtherIncomeRouteImport } from './routes/_authenticated/other-income'
import { Route as AuthenticatedOutletsRouteImport } from './routes/_authenticated/outlets'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSalesStockDayRouteImport } from './routes/_authenticated/sales-stock-day'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedStockOpeningRouteImport } from './routes/_authenticated/stock-opening'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTeamAccessRouteImport } from './routes/_authenticated/team-access'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTravelFundsRouteImport } from './routes/_authenticated/travel-funds'
import { Route as AuthenticatedVisitRouteImport } from './routes/_authenticated/visit'
import { Route as AuthenticatedWarehouseDirectSaleRouteImport } from './routes/_authenticated/warehouse-direct-sale'
import { Route as AuthenticatedFeaturePreviewFeatureRouteImport } from './routes/_authenticated/feature-preview.$feature'
import { Route as AuthenticatedOutletsNewRouteImport } from './routes/_authenticated/outlets.new'
import { Route as AuthenticatedReceiptIdRouteImport } from './routes/_authenticated/receipt.$id'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions.index'
import { Route as AuthenticatedOutletsIdEditRouteImport } from './routes/_authenticated/outlets.$id.edit'
import { Route as AuthenticatedTransactionsIdEditRouteImport } from './routes/_authenticated/transactions.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStockResetRoute =
  AuthenticatedAdminStockResetRouteImport.update({
    id: '/admin-stock-reset',
    path: '/admin-stock-reset',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterStockRoute =
  AuthenticatedMasterStockRouteImport.update({
    id: '/master-stock',
    path: '/master-stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperasionalSalesRoute =
  AuthenticatedOperasionalSalesRouteImport.update({
    id: '/operasional-sales',
    path: '/operasional-sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOtherIncomeRoute =
  AuthenticatedOtherIncomeRouteImport.update({
    id: '/other-income',
    path: '/other-income',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutletsRoute = AuthenticatedOutletsRouteImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesStockDayRoute =
  AuthenticatedSalesStockDayRouteImport.update({
    id: '/sales-stock-day',
    path: '/sales-stock-day',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockOpeningRoute =
  AuthenticatedStockOpeningRouteImport.update({
    id: '/stock-opening',
    path: '/stock-opening',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamAccessRoute = AuthenticatedTeamAccessRouteImport.update({
  id: '/team-access',
  path: '/team-access',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTravelFundsRoute =
  AuthenticatedTravelFundsRouteImport.update({
    id: '/travel-funds',
    path: '/travel-funds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitRoute = AuthenticatedVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarehouseDirectSaleRoute =
  AuthenticatedWarehouseDirectSaleRouteImport.update({
    id: '/warehouse-direct-sale',
    path: '/warehouse-direct-sale',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeaturePreviewFeatureRoute =
  AuthenticatedFeaturePreviewFeatureRouteImport.update({
    id: '/feature-preview/$feature',
    path: '/feature-preview/$feature',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutletsNewRoute = AuthenticatedOutletsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedOutletsRoute,
} as any)
const AuthenticatedReceiptIdRoute = AuthenticatedReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedOutletsIdEditRoute =
  AuthenticatedOutletsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedOutletsRoute,
  } as any)
const AuthenticatedTransactionsIdEditRoute =
  AuthenticatedTransactionsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-stock-reset': typeof AuthenticatedAdminStockResetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/master-stock': typeof AuthenticatedMasterStockRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/operasional-sales': typeof AuthenticatedOperasionalSalesRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/other-income': typeof AuthenticatedOtherIncomeRoute
  '/outlets': typeof AuthenticatedOutletsRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-stock-day': typeof AuthenticatedSalesStockDayRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/stock-opening': typeof AuthenticatedStockOpeningRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-access': typeof AuthenticatedTeamAccessRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/travel-funds': typeof AuthenticatedTravelFundsRoute
  '/visit': typeof AuthenticatedVisitRoute
  '/warehouse-direct-sale': typeof AuthenticatedWarehouseDirectSaleRoute
  '/feature-preview/$feature': typeof AuthenticatedFeaturePreviewFeatureRoute
  '/outlets/new': typeof AuthenticatedOutletsNewRoute
  '/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/outlets/$id/edit': typeof AuthenticatedOutletsIdEditRoute
  '/transactions/$id/edit': typeof AuthenticatedTransactionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-stock-reset': typeof AuthenticatedAdminStockResetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/master-stock': typeof AuthenticatedMasterStockRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/operasional-sales': typeof AuthenticatedOperasionalSalesRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/other-income': typeof AuthenticatedOtherIncomeRoute
  '/outlets': typeof AuthenticatedOutletsRouteWithChildren
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-stock-day': typeof AuthenticatedSalesStockDayRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/stock-opening': typeof AuthenticatedStockOpeningRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-access': typeof AuthenticatedTeamAccessRoute
  '/travel-funds': typeof AuthenticatedTravelFundsRoute
  '/visit': typeof AuthenticatedVisitRoute
  '/warehouse-direct-sale': typeof AuthenticatedWarehouseDirectSaleRoute
  '/feature-preview/$feature': typeof AuthenticatedFeaturePreviewFeatureRoute
  '/outlets/new': typeof AuthenticatedOutletsNewRoute
  '/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/outlets/$id/edit': typeof AuthenticatedOutletsIdEditRoute
  '/transactions/$id/edit': typeof AuthenticatedTransactionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-stock-reset': typeof AuthenticatedAdminStockResetRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/master-stock': typeof AuthenticatedMasterStockRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/operasional-sales': typeof AuthenticatedOperasionalSalesRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/other-income': typeof AuthenticatedOtherIncomeRoute
  '/_authenticated/outlets': typeof AuthenticatedOutletsRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales-stock-day': typeof AuthenticatedSalesStockDayRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/stock-opening': typeof AuthenticatedStockOpeningRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/team-access': typeof AuthenticatedTeamAccessRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/_authenticated/travel-funds': typeof AuthenticatedTravelFundsRoute
  '/_authenticated/visit': typeof AuthenticatedVisitRoute
  '/_authenticated/warehouse-direct-sale': typeof AuthenticatedWarehouseDirectSaleRoute
  '/_authenticated/feature-preview/$feature': typeof AuthenticatedFeaturePreviewFeatureRoute
  '/_authenticated/outlets/new': typeof AuthenticatedOutletsNewRoute
  '/_authenticated/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/outlets/$id/edit': typeof AuthenticatedOutletsIdEditRoute
  '/_authenticated/transactions/$id/edit': typeof AuthenticatedTransactionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin-stock-reset'
    | '/dashboard'
    | '/expenses'
    | '/master-stock'
    | '/notes'
    | '/operasional-sales'
    | '/operations'
    | '/other-income'
    | '/outlets'
    | '/products'
    | '/profile'
    | '/reminders'
    | '/reports'
    | '/sales-stock-day'
    | '/schedule'
    | '/stock-opening'
    | '/team'
    | '/team-access'
    | '/transactions'
    | '/travel-funds'
    | '/visit'
    | '/warehouse-direct-sale'
    | '/feature-preview/$feature'
    | '/outlets/new'
    | '/receipt/$id'
    | '/transactions/'
    | '/outlets/$id/edit'
    | '/transactions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin-stock-reset'
    | '/dashboard'
    | '/expenses'
    | '/master-stock'
    | '/notes'
    | '/operasional-sales'
    | '/operations'
    | '/other-income'
    | '/outlets'
    | '/products'
    | '/profile'
    | '/reminders'
    | '/reports'
    | '/sales-stock-day'
    | '/schedule'
    | '/stock-opening'
    | '/team'
    | '/team-access'
    | '/travel-funds'
    | '/visit'
    | '/warehouse-direct-sale'
    | '/feature-preview/$feature'
    | '/outlets/new'
    | '/receipt/$id'
    | '/transactions'
    | '/outlets/$id/edit'
    | '/transactions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin-stock-reset'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/master-stock'
    | '/_authenticated/notes'
    | '/_authenticated/operasional-sales'
    | '/_authenticated/operations'
    | '/_authenticated/other-income'
    | '/_authenticated/outlets'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/sales-stock-day'
    | '/_authenticated/schedule'
    | '/_authenticated/stock-opening'
    | '/_authenticated/team'
    | '/_authenticated/team-access'
    | '/_authenticated/transactions'
    | '/_authenticated/travel-funds'
    | '/_authenticated/visit'
    | '/_authenticated/warehouse-direct-sale'
    | '/_authenticated/feature-preview/$feature'
    | '/_authenticated/outlets/new'
    | '/_authenticated/receipt/$id'
    | '/_authenticated/transactions/'
    | '/_authenticated/outlets/$id/edit'
    | '/_authenticated/transactions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-stock-reset': {
      id: '/_authenticated/admin-stock-reset'
      path: '/admin-stock-reset'
      fullPath: '/admin-stock-reset'
      preLoaderRoute: typeof AuthenticatedAdminStockResetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-stock': {
      id: '/_authenticated/master-stock'
      path: '/master-stock'
      fullPath: '/master-stock'
      preLoaderRoute: typeof AuthenticatedMasterStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operasional-sales': {
      id: '/_authenticated/operasional-sales'
      path: '/operasional-sales'
      fullPath: '/operasional-sales'
      preLoaderRoute: typeof AuthenticatedOperasionalSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-income': {
      id: '/_authenticated/other-income'
      path: '/other-income'
      fullPath: '/other-income'
      preLoaderRoute: typeof AuthenticatedOtherIncomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outlets': {
      id: '/_authenticated/outlets'
      path: '/outlets'
      fullPath: '/outlets'
      preLoaderRoute: typeof AuthenticatedOutletsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-stock-day': {
      id: '/_authenticated/sales-stock-day'
      path: '/sales-stock-day'
      fullPath: '/sales-stock-day'
      preLoaderRoute: typeof AuthenticatedSalesStockDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-opening': {
      id: '/_authenticated/stock-opening'
      path: '/stock-opening'
      fullPath: '/stock-opening'
      preLoaderRoute: typeof AuthenticatedStockOpeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-access': {
      id: '/_authenticated/team-access'
      path: '/team-access'
      fullPath: '/team-access'
      preLoaderRoute: typeof AuthenticatedTeamAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travel-funds': {
      id: '/_authenticated/travel-funds'
      path: '/travel-funds'
      fullPath: '/travel-funds'
      preLoaderRoute: typeof AuthenticatedTravelFundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visit': {
      id: '/_authenticated/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof AuthenticatedVisitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouse-direct-sale': {
      id: '/_authenticated/warehouse-direct-sale'
      path: '/warehouse-direct-sale'
      fullPath: '/warehouse-direct-sale'
      preLoaderRoute: typeof AuthenticatedWarehouseDirectSaleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feature-preview/$feature': {
      id: '/_authenticated/feature-preview/$feature'
      path: '/feature-preview/$feature'
      fullPath: '/feature-preview/$feature'
      preLoaderRoute: typeof AuthenticatedFeaturePreviewFeatureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outlets/new': {
      id: '/_authenticated/outlets/new'
      path: '/new'
      fullPath: '/outlets/new'
      preLoaderRoute: typeof AuthenticatedOutletsNewRouteImport
      parentRoute: typeof AuthenticatedOutletsRoute
    }
    '/_authenticated/receipt/$id': {
      id: '/_authenticated/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof AuthenticatedReceiptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/outlets/$id/edit': {
      id: '/_authenticated/outlets/$id/edit'
      path: '/$id/edit'
      fullPath: '/outlets/$id/edit'
      preLoaderRoute: typeof AuthenticatedOutletsIdEditRouteImport
      parentRoute: typeof AuthenticatedOutletsRoute
    }
    '/_authenticated/transactions/$id/edit': {
      id: '/_authenticated/transactions/$id/edit'
      path: '/$id/edit'
      fullPath: '/transactions/$id/edit'
      preLoaderRoute: typeof AuthenticatedTransactionsIdEditRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
  }
}

interface AuthenticatedOutletsRouteChildren {
  AuthenticatedOutletsNewRoute: typeof AuthenticatedOutletsNewRoute
  AuthenticatedOutletsIdEditRoute: typeof AuthenticatedOutletsIdEditRoute
}

const AuthenticatedOutletsRouteChildren: AuthenticatedOutletsRouteChildren = {
  AuthenticatedOutletsNewRoute: AuthenticatedOutletsNewRoute,
  AuthenticatedOutletsIdEditRoute: AuthenticatedOutletsIdEditRoute,
}

const AuthenticatedOutletsRouteWithChildren =
  AuthenticatedOutletsRoute._addFileChildren(AuthenticatedOutletsRouteChildren)

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedTransactionsIdEditRoute: typeof AuthenticatedTransactionsIdEditRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
    AuthenticatedTransactionsIdEditRoute: AuthenticatedTransactionsIdEditRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminStockResetRoute: typeof AuthenticatedAdminStockResetRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedMasterStockRoute: typeof AuthenticatedMasterStockRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedOperasionalSalesRoute: typeof AuthenticatedOperasionalSalesRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedOtherIncomeRoute: typeof AuthenticatedOtherIncomeRoute
  AuthenticatedOutletsRoute: typeof AuthenticatedOutletsRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesStockDayRoute: typeof AuthenticatedSalesStockDayRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedStockOpeningRoute: typeof AuthenticatedStockOpeningRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTeamAccessRoute: typeof AuthenticatedTeamAccessRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
  AuthenticatedTravelFundsRoute: typeof AuthenticatedTravelFundsRoute
  AuthenticatedVisitRoute: typeof AuthenticatedVisitRoute
  AuthenticatedWarehouseDirectSaleRoute: typeof AuthenticatedWarehouseDirectSaleRoute
  AuthenticatedFeaturePreviewFeatureRoute: typeof AuthenticatedFeaturePreviewFeatureRoute
  AuthenticatedReceiptIdRoute: typeof AuthenticatedReceiptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminStockResetRoute: AuthenticatedAdminStockResetRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedMasterStockRoute: AuthenticatedMasterStockRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedOperasionalSalesRoute: AuthenticatedOperasionalSalesRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedOtherIncomeRoute: AuthenticatedOtherIncomeRoute,
  AuthenticatedOutletsRoute: AuthenticatedOutletsRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesStockDayRoute: AuthenticatedSalesStockDayRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedStockOpeningRoute: AuthenticatedStockOpeningRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTeamAccessRoute: AuthenticatedTeamAccessRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
  AuthenticatedTravelFundsRoute: AuthenticatedTravelFundsRoute,
  AuthenticatedVisitRoute: AuthenticatedVisitRoute,
  AuthenticatedWarehouseDirectSaleRoute: AuthenticatedWarehouseDirectSaleRoute,
  AuthenticatedFeaturePreviewFeatureRoute:
    AuthenticatedFeaturePreviewFeatureRoute,
  AuthenticatedReceiptIdRoute: AuthenticatedReceiptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
