/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedVisitRouteImport } from './routes/_authenticated/visit'
import { Route as AuthenticatedOutletsNewRouteImport } from './routes/_authenticated/outlets.new'
import { Route as AuthenticatedReceiptIdRouteImport } from './routes/_authenticated/receipt.$id'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions.index'
import { Route as AuthenticatedTransactionsIdEditRouteImport } from './routes/_authenticated/transactions.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitRoute = AuthenticatedVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutletsNewRoute = AuthenticatedOutletsNewRouteImport.update({
  id: '/outlets/new',
  path: '/outlets/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptIdRoute = AuthenticatedReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedTransactionsIdEditRoute =
  AuthenticatedTransactionsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/visit': typeof AuthenticatedVisitRoute
  '/outlets/new': typeof AuthenticatedOutletsNewRoute
  '/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/transactions/$id/edit': typeof AuthenticatedTransactionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/visit': typeof AuthenticatedVisitRoute
  '/outlets/new': typeof AuthenticatedOutletsNewRoute
  '/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/transactions/$id/edit': typeof AuthenticatedTransactionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/_authenticated/visit': typeof AuthenticatedVisitRoute
  '/_authenticated/outlets/new': typeof AuthenticatedOutletsNewRoute
  '/_authenticated/receipt/$id': typeof AuthenticatedReceiptIdRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/transactions/$id/edit': typeof AuthenticatedTransactionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/products'
    | '/profile'
    | '/reports'
    | '/team'
    | '/transactions'
    | '/visit'
    | '/outlets/new'
    | '/receipt/$id'
    | '/transactions/'
    | '/transactions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/products'
    | '/profile'
    | '/reports'
    | '/team'
    | '/visit'
    | '/outlets/new'
    | '/receipt/$id'
    | '/transactions'
    | '/transactions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/team'
    | '/_authenticated/transactions'
    | '/_authenticated/visit'
    | '/_authenticated/outlets/new'
    | '/_authenticated/receipt/$id'
    | '/_authenticated/transactions/'
    | '/_authenticated/transactions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visit': {
      id: '/_authenticated/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof AuthenticatedVisitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outlets/new': {
      id: '/_authenticated/outlets/new'
      path: '/outlets/new'
      fullPath: '/outlets/new'
      preLoaderRoute: typeof AuthenticatedOutletsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipt/$id': {
      id: '/_authenticated/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof AuthenticatedReceiptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/transactions/$id/edit': {
      id: '/_authenticated/transactions/$id/edit'
      path: '/$id/edit'
      fullPath: '/transactions/$id/edit'
      preLoaderRoute: typeof AuthenticatedTransactionsIdEditRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
  }
}

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedTransactionsIdEditRoute: typeof AuthenticatedTransactionsIdEditRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
    AuthenticatedTransactionsIdEditRoute: AuthenticatedTransactionsIdEditRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
  AuthenticatedVisitRoute: typeof AuthenticatedVisitRoute
  AuthenticatedOutletsNewRoute: typeof AuthenticatedOutletsNewRoute
  AuthenticatedReceiptIdRoute: typeof AuthenticatedReceiptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
  AuthenticatedVisitRoute: AuthenticatedVisitRoute,
  AuthenticatedOutletsNewRoute: AuthenticatedOutletsNewRoute,
  AuthenticatedReceiptIdRoute: AuthenticatedReceiptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
